name: Documentation
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "type: documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please describe what needs to be documented or corrected.
  
  - type: dropdown
    id: state
    attributes:
      label: State
      description: Current state of this issue (will be updated by maintainers)
      options:
        - New
        - Reviewed and Acknowledged
        - Reviewed and Working as Designed
        - In Progress
        - Complete
      default: 0
    validations:
      required: true
  
  - type: dropdown
    id: documentation-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Documentation
        - Unclear Documentation
        - Outdated Documentation
        - Example or Tutorial Request
      default: 0
    validations:
      required: true
  
  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located (or where should it be)?
      placeholder: |
        - Page/File: [e.g. README.md, API Reference]
        - Section: [e.g. Getting Started]
        - URL: [if applicable]
    validations:
      required: true
  
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's missing, incorrect, or unclear
      placeholder: Describe the documentation issue...
    validations:
      required: true
  
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: What should the documentation say or include?
      placeholder: The documentation should explain...
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Add additional context here...
    validations:
      required: false
